### ISSUE TITLE
I can't get it to work!

### ISSUE THREAD

**Issue by fariss** [hamada2029/netflix-override-bug#1]
Hello;

Can you explain to me how to edit, save and map this? 
I've tried so many times, and I end up with broken Netflix.

Thank you 👍

**Comment by hamada2029** [comment]
Excuse me for lack of explanation.
Downloaded file from copied link is for editing.
You can edit it by any text editor.
Mapping is environment dependent.
https://veerasundar.com/blog/2016/05/charles-proxy-map-local/
This link is one example.
Map JavaScript file URL to edited local file. 

If you have any trouble on Netflix by my fix,
You quit Charles it will return to the previous state at least.
Please tell me if you have some questions.

I'm finding easy other fix. But it's hard to.
Thanks.

**Comment by fariss** [comment]
__Yay_!_ it worked.
